### PR TITLE
Sly/incremental repair support

### PR DESCRIPTION
**Pull request by djsly**
Starting with Cassandra 2.1.X , the repair feature requires a new parameter related to incremental mode. 

This PR force the usage of Cassandra 2.1.X API and enables the incremental repair parameter

### CODE REVIEW

**Comment by zznate** [comment]
@djsly Just sent a PR to Nuance fork that should fix the merge conflicts so this can be brought back into spotify's repo.

**Comment by Bj0rnen** [comment]
I have looked at the commits here, and they seem fine. We will hold off on testing this until the Nuance fork is sorted out. Am I correct in assuming this isn't compatible with 2.0 clusters because of the extra argument to the forceRepairRangeAsync method?

**Comment by zznate** [comment]
> Am I correct in assuming this isn't compatible with 2.0 clusters because of the extra argument to the forceRepairRangeAsync method?

Good point (I actually did not verify with 2.0). If this is the case, I'd like to see this be backwards compatible and am willing to work on that. I'd like to propose we do this under a separate ticket though so we can sort this merge out first.

**Comment by djsly** [comment]
Correct, this isn't backward compatible.

**Pull request closed without merging**
